const ADMIN_EMAIL='ganaa.ganaa0731@gmail.com';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const text=(v,max=100)=>typeof v==='string'?v.trim().slice(0,max):'';
function db(env){if(!env.DB)throw new HttpError('Мэдээллийн сан түр боломжгүй байна. Дахин оролдоно уу.',503);return env.DB;}
function identity(request){const id=request.headers.get('oai-authenticated-user-id');const email=request.headers.get('oai-authenticated-user-email');const admin=email?.trim().toLowerCase()===ADMIN_EMAIL;return id||admin?{id:id||'owner:'+ADMIN_EMAIL,email:email||'',admin}:null;}
async function body(request){const raw=await request.text();if(raw.length>40000)throw new HttpError('Мэдээлэл хэт урт байна.',413);try{return JSON.parse(raw);}catch{throw new HttpError('Мэдээллийн бүтэц буруу байна.');}}
function parsed(row){return {...row,progress:JSON.parse(row.progress),assignments:JSON.parse(row.assignments),submissions:JSON.parse(row.submissions)};}
export function validateApplication(b){const firstName=text(b.firstName,60),lastName=text(b.lastName,60),name=lastName+' '+firstName,age=Number(b.age),email=text(b.email,254).toLowerCase(),guardianName=text(b.guardianName,100),school=text(b.school,150),grade=text(b.grade,20),phone=text(b.phone,20).replace(/[ -]/g,'').replace(/^\+976/,'');if(firstName.length<2||lastName.length<2||guardianName.length<2||!/^\S+@[^\s@]+\.[^\s@]+$/.test(email)||!['','preschool','other',...Array.from({length:12},(_,i)=>String(i+1))].includes(grade)||!Number.isInteger(age)||age<5||age>99||!['beginner','intermediate','advanced'].includes(b.level)||!['Танхим','Онлайн'].includes(b.mode)||!/^\d{8}$/.test(phone)||b.consent!==true||!/^[-a-zA-Z0-9]{20,60}$/.test(b.id||''))throw new HttpError('Суралцагч болон асран хамгаалагчийн нэр, нас, имэйл, утас, зөвшөөрлөө шалгана уу.');return {id:b.id,name,firstName,lastName,email,guardianName,school,grade,age,phone,level:b.level,mode:b.mode,notes:text(b.notes,1000)};}
export function validateProgress(p){if(!p||typeof p!=='object')throw new HttpError('Үнэлгээ буруу байна.');const attendance=Array.isArray(p.attendance)?p.attendance:[];const ratings=Array.isArray(p.ratings)?p.ratings:[];if(attendance.length>366||ratings.length>100)throw new HttpError('Мөрийн тоо хэтэрсэн.');for(const x of attendance){if(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!['present','late','excused','absent'].includes(x.status)||!Number.isFinite(x.hours)||x.hours<0||x.hours>12)throw new HttpError('Ирцийн мөр буруу.');}for(const x of ratings){if(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!Number.isInteger(x.rating)||x.rating<100||x.rating>3500)throw new HttpError('Чансааны мөр буруу.');}if(!Array.isArray(p.skills)||p.skills.length!==5||p.skills.some(x=>!Number.isFinite(x)||x<0||x>100))throw new HttpError('Таван ур чадвар 0–100 байна.');return {attendance,ratings,skills:p.skills,review:text(p.review,3000),coach:text(p.coach),className:text(p.className,40),updated:new Date().toISOString()};}
export async function handleAPI(request,env){const url=new URL(request.url),path=url.pathname,user=identity(request);if(request.method!=='GET'){if(request.headers.get('Origin')!==url.origin)throw new HttpError('Хүсэлтийн эх сурвалж зөвшөөрөгдөөгүй.',403);if(!request.headers.get('Content-Type')?.includes('application/json'))throw new HttpError('JSON хүсэлт шаардлагатай.',415);}
if(path==='/api/config'&&request.method==='GET'){const row=await db(env).prepare('SELECT value FROM settings WHERE key = ?').bind('contact').first();return json(row?JSON.parse(row.value):{phone:'',messenger:'',whatsapp:'',address:''});}
if(path==='/api/content'&&request.method==='GET'){const row=await db(env).prepare('SELECT value FROM settings WHERE key = ?').bind('content').first();return json(row?JSON.parse(row.value):{values:{},updated:null});}
if(!user)throw new HttpError('Хувийн танхимд нэвтэрнэ үү.',401);
if(path==='/api/me'&&request.method==='GET')return json(user);
if(path==='/api/applications'&&request.method==='POST'){const b=validateApplication(await body(request));const existing=await db(env).prepare('SELECT id, owner FROM applications WHERE id = ?').bind(b.id).first();if(existing){if(existing.owner!==user.id)throw new HttpError('Бүртгэлийн дугаар давхардсан.',409);return json({id:b.id,status:'saved'});}const count=await db(env).prepare("SELECT COUNT(*) AS n FROM applications WHERE owner = ? AND created > ?").bind(user.id,new Date(Date.now()-86400000).toISOString()).first();if(count.n>=10)throw new HttpError('Өнөөдрийн бүртгэлийн хязгаарт хүрсэн байна.',429);await db(env).prepare('INSERT INTO applications (id,owner,name,age,level,mode,phone,notes,created,first_name,last_name,email,guardian_name,school,grade) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.id,user.id,b.name,b.age,b.level,b.mode,b.phone,b.notes,new Date().toISOString(),b.firstName,b.lastName,b.email,b.guardianName,b.school,b.grade).run();return json({id:b.id,status:'saved'},201);}
if(path==='/api/students'&&request.method==='GET'){const rows=await db(env).prepare('SELECT * FROM applications WHERE owner = ? ORDER BY created DESC').bind(user.id).all();return json(rows.results.map(parsed));}
const submission=path.match(/^\/api\/students\/([-\w]+)\/submissions$/);if(submission&&request.method==='POST'){const row=await db(env).prepare('SELECT * FROM applications WHERE id = ? AND owner = ?').bind(submission[1],user.id).first();if(!row)throw new HttpError('Сурагч олдсонгүй.',404);const b=await body(request),tasks=JSON.parse(row.assignments);if(!tasks.some(t=>t.id===b.taskId))throw new HttpError('Даалгавар олдсонгүй.',404);const answer=text(b.answer,5000);if(!answer)throw new HttpError('Хариулт оруулна уу.');const response={answer,submitted:new Date().toISOString(),feedback:''};await db(env).prepare('UPDATE applications SET submissions = json_set(submissions, ?, json(?)) WHERE id = ? AND owner = ?').bind('$.'+b.taskId,JSON.stringify(response),row.id,user.id).run();return json({status:'saved'});}
if(!path.startsWith('/api/admin/'))throw new HttpError('Олдсонгүй.',404);if(!user.admin)throw new HttpError('Зөвхөн академийн удирдлагад нээлттэй.',403);
if(path==='/api/admin/content'&&request.method==='PATCH'){const b=await body(request);if(!b.values||typeof b.values!=='object'||Array.isArray(b.values)||Object.keys(b.values).length>400)throw new HttpError('Агуулгын бүтэц буруу.');for(const [key,value] of Object.entries(b.values)){if(!/^content-[a-z0-9-]{1,80}$/.test(key)||typeof value!=='string'||value.length>3000)throw new HttpError('Агуулгын талбар буруу.');}const row=await db(env).prepare('SELECT value FROM settings WHERE key = ?').bind('content').first();const value={values:{...(row?JSON.parse(row.value).values:{}),...b.values},updated:new Date().toISOString()};await db(env).prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('content',JSON.stringify(value)).run();return json(value);}
const profile=path.match(/^\/api\/admin\/students\/([-\w]+)\/profile$/);if(profile&&request.method==='PATCH'){const row=await db(env).prepare('SELECT id FROM applications WHERE id = ?').bind(profile[1]).first();if(!row)throw new HttpError('Сурагч олдсонгүй.',404);const b=validateApplication({...await body(request),id:row.id,consent:true});await db(env).prepare('UPDATE applications SET name=?,first_name=?,last_name=?,age=?,level=?,mode=?,phone=?,email=?,guardian_name=?,school=?,grade=?,notes=? WHERE id=?').bind(b.name,b.firstName,b.lastName,b.age,b.level,b.mode,b.phone,b.email,b.guardianName,b.school,b.grade,b.notes,row.id).run();return json({status:'saved'});}
const taskEdit=path.match(/^\/api\/admin\/students\/([-\w]+)\/tasks\/([-\w]+)$/);if(taskEdit&&['PATCH','DELETE'].includes(request.method)){const row=await db(env).prepare('SELECT assignments FROM applications WHERE id = ?').bind(taskEdit[1]).first();if(!row)throw new HttpError('Сурагч олдсонгүй.',404);const list=JSON.parse(row.assignments),i=list.findIndex(t=>t.id===taskEdit[2]);if(i<0)throw new HttpError('Даалгавар олдсонгүй.',404);if(request.method==='DELETE'){list.splice(i,1);}else{const b=await body(request),title=text(b.title,200),instruction=text(b.instruction,3000);if(!title||!instruction)throw new HttpError('Гарчиг, даалгавраа оруулна уу.');list[i]={...list[i],title,instruction};}await db(env).prepare('UPDATE applications SET assignments = ? WHERE id = ?').bind(JSON.stringify(list),taskEdit[1]).run();return json({status:'saved'});}
if(path==='/api/admin/students'&&request.method==='GET'){const rows=await db(env).prepare('SELECT * FROM applications ORDER BY created DESC LIMIT 500').all();return json(rows.results.map(parsed));}
if(path==='/api/admin/contact'&&request.method==='POST'){const b=await body(request),contact={phone:text(b.phone,20),whatsapp:text(b.whatsapp,20),messenger:text(b.messenger,200),address:text(b.address,300)};if(contact.phone&&!/^\+?\d{8,15}$/.test(contact.phone))throw new HttpError('Утас буруу байна.');if(contact.whatsapp&&!/^\d{8,15}$/.test(contact.whatsapp))throw new HttpError('WhatsApp дугаар зөвхөн тоо байна.');if(contact.messenger&&!/^https:\/\/(www\.)?(m\.me|messenger\.com|facebook\.com)\//.test(contact.messenger))throw new HttpError('Messenger холбоос буруу байна.');await db(env).prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('contact',JSON.stringify(contact)).run();return json({status:'saved'});}
const edit=path.match(/^\/api\/admin\/students\/([-\w]+)$/);if(edit&&request.method==='PATCH'){const b=await body(request);if(!['new','contacted','active','closed'].includes(b.status))throw new HttpError('Төлөв буруу.');const progress=validateProgress(b.progress);const row=await db(env).prepare('SELECT id FROM applications WHERE id = ?').bind(edit[1]).first();if(!row)throw new HttpError('Сурагч олдсонгүй.',404);await db(env).prepare('UPDATE applications SET status = ?, progress = ? WHERE id = ?').bind(b.status,JSON.stringify(progress),edit[1]).run();return json({status:'saved'});}
const tasks=path.match(/^\/api\/admin\/students\/([-\w]+)\/tasks$/);if(tasks&&request.method==='POST'){const row=await db(env).prepare('SELECT assignments FROM applications WHERE id = ?').bind(tasks[1]).first();if(!row)throw new HttpError('Сурагч олдсонгүй.',404);const b=await body(request),title=text(b.title,200),instruction=text(b.instruction,3000);if(!title||!instruction)throw new HttpError('Гарчиг болон даалгавар оруулна уу.');const list=JSON.parse(row.assignments);if(list.length>=100)throw new HttpError('Даалгаврын хязгаарт хүрсэн.');list.push({id:crypto.randomUUID(),title,instruction,created:new Date().toISOString()});await db(env).prepare('UPDATE applications SET assignments = ? WHERE id = ?').bind(JSON.stringify(list),tasks[1]).run();return json({status:'saved'});}
const feedback=path.match(/^\/api\/admin\/students\/([-\w]+)\/feedback$/);if(feedback&&request.method==='POST'){const b=await body(request);if(!/^[-\w]{20,60}$/.test(b.taskId||''))throw new HttpError('Даалгаврын дугаар буруу.');await db(env).prepare('UPDATE applications SET submissions = json_set(submissions, ?, ?) WHERE id = ? AND json_type(submissions, ?) IS NOT NULL').bind('$.'+b.taskId+'.feedback',text(b.feedback,3000),feedback[1],'$.'+b.taskId).run();return json({status:'saved'});}
throw new HttpError('Олдсонгүй.',404);}
export default {async fetch(request,env){try{const path=new URL(request.url).pathname;if(path.startsWith('/api/'))return await handleAPI(request,env);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});const key=['/','/portal','/admin'].includes(path)?'/index.html':path;const asset=ASSETS[key];if(!asset)return new Response('Хуудас олдсонгүй',{status:404});const bytes=Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0));return new Response(request.method==='HEAD'?null:bytes,{headers:{'Content-Type':asset.type,'Cache-Control':asset.type.startsWith('text/')?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'"}});}catch(error){return json({error:error.status?error.message:'Үйлчилгээ түр боломжгүй байна. Мэдээллээ хадгалаад дахин оролдоно уу.'},error.status||503);}}};
